-- MySQL Administrator dump 1.4
--
-- ------------------------------------------------------
-- Server version	5.1.73-log


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


--
-- Create schema drupal_data_fba_org_uk_test1
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ drupal_data_fba_org_uk_test1;
USE drupal_data_fba_org_uk_test1;

--
-- Table structure for table `drupal_data_fba_org_uk_test1`.`islandora_autocomplete`
--

DROP TABLE IF EXISTS `islandora_autocomplete`;
CREATE TABLE `islandora_autocomplete` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `description` varchar(256) NOT NULL,
  `source` varchar(64) NOT NULL,
  `fields` int(11) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  KEY `source` (`source`)
) ENGINE=MyISAM AUTO_INCREMENT=44 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `drupal_data_fba_org_uk_test1`.`islandora_autocomplete`
--

/*!40000 ALTER TABLE `islandora_autocomplete` DISABLE KEYS */;
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (5,'sp_ol_xxxx_pvocab_mads_usedfor_npvocab_mads_use','Controls the Object Linker processing for the \"Use For Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Use Term\" field on a Non-preferred Vocab MADS \"Object\" Record','sparql',1),
 (4,'sp_ol_xxxx_pvocab_mads_broader_pvocab_mads_narrower','Controls the Object Linker processing for the \"Broader Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Narrower Term\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (7,'sp_ol_xxxx_pdf_mods_vocabkeyw_pvocab_mads_xxxx','Controls the Object Linker processing for the \"Vocab Keyword\" on a PDF \"Subject\" Record linking to a Preferred Vocab \"Object\" Record.','sparql',1),
 (31,'sp_ol_xxxx_fbalib_mods_taxonkeyw_taxon_dwc_xxxx','Controls the Object Linker processing for the \"Taxonomic Keyword\" on an FBA Library \"Subject\" Record linking to a Taxonomic \"Object\" Record.','sparql',1),
 (32,'sp_ol_xxxx_taxon_dwc_creationdate_fbalib_mods_xxxx','Controls the Object Linker processing for removing links between Taxon \"Subject\" Records and FBA PDF MODS \"Object\" Records when a Taxon Record is purged after one or more FBA Library Records have been linked to it.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (10,'sp_ol_xxxx_pdf_mods_geokeyw_pgeovoc_mads_xxxx','Controls the Object Linker processing for the \"geographic keyword\" on a PDF \"Subject\" Record linking to a Preferred geoVocab \"Object\" Record.','sparql',1),
 (11,'sp_ol_xxxx_pvocab_mads_related_pvocab_mads_related','Controls the Object Linker processing for the \"Related Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Related Term\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (12,'sp_ol_xxxx_pvocab_mads_narrower_pvocab_mads_broader','Controls the Object Linker processing for the \"Narrower Term\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Broader Term\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (13,'sp_ol_xxxx_pgeovoc_mads_broader_pgeovoc_mads_narrower','Controls the Object Linker processing for the \"Broader Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Narrower Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (14,'sp_ol_xxxx_pgeovoc_mads_narrower_pgeovoc_mads_broader','Controls the Object Linker processing for the \"Narrower Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Broader Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (15,'sp_ol_xxxx_pgeovoc_mads_related_pgeovoc_mads_related','Controls the Object Linker processing for the \"Related Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Related Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (16,'sp_ol_xxxx_pgeovoc_mads_usedfor_npgeovoc_mads_use','Controls the Object Linker processing for the \"Used For Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Use Term\" field on a Non-preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (17,'sp_ol_xxxx_pgeovoc_mads_geofeature_pgeovoc_mads_isgeofeatureof','Controls the Object Linker processing for the \"Geographic Feature Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Is Geographic Feature Of Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (18,'sp_ol_xxxx_pgeovoc_mads_isgeofeatureof_pgeovoc_mads_geofeature','Controls the Object Linker processing for the \"Is Geographic Feature Of Term\" field on a Preferred geoVocab MADS \"Subject\" Record linking to a \"Geographic Feature Term\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1),
 (19,'sp_ol_xxxx_npgeovoc_mads_use_pgeovoc_mads_usedfor','Controls the Object Linker processing for the \"Use\" field on a Non-preferred geoVocab MADS \"Subject\" Record linking to a \"Used For\" field on a Preferred geoVocab MADS \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (20,'sp_ol_xxxx_npvocab_mads_use_pvocab_mads_usedfor','Controls the Object Linker processing for the \"Use\" field on a Non-preferred Vocab MADS \"Subject\" Record linking to a \"Used For\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (21,'sp_ol_xxxx_pgeovoc_mads_creationdate_pdf_mods_xxxx','Controls the Object Linker processing for removing links between Preferred geoVocab \"Subject\" Records and PDF MADS \"Object\" Records when a Preferrred geoVocab Record is purged after one or more PDF Records have been linked to it. ','sparql',1),
 (22,'sp_ol_xxxx_pvocab_mads_creationdate_pdf_mods_xxxx','Controls the Object Linker processing for removing links between Preferred Vocab \"Subject\" Records and PDF MODS \"Object\" Records when a Preferrred Vocab Record is purged after one or more PDF Records have been linked to it.','sparql',1),
 (23,'sp_ol_xxxx_fbalib_mods_vocabkeyw_pvocab_mads_xxxx','Controls the Object Linker processing for the \"Vocab Keyword\" on an FBA Library \"Subject\" Record linking to a Preferred Vocab \"Object\" Record.','sparql',1),
 (24,'sp_ol_xxxx_fbalib_mods_geokeyw_pgeovoc_mads_xxxx','Controls the Object Linker processing for the \"geographic keyword\" on an fba library \"Subject\" Record linking to a Preferred geoVocab \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (25,'sp_ol_xxxx_pvocab_mads_punit_pvocab_mads_xxxx','Controls the Object Linker processing for the \"Preferred Unit\" field on a Preferred Vocab MADS \"Subject\" Record autocompleting on the list of preferred terms.','sparql',1),
 (26,'sp_ol_xxxx_pvocab_mads_approveddate_pvocab_mads_xxxx','Controls the Object Linker processing for removing hasPreferredUnit links between Preferred Vocab MADS \"Subject\" Records and a Preferred Unit Record when the Preferred Unit Record is purged.','sparql',1),
 (27,'sp_ol_xxxx_pvocab_mads_creationdate_fbalib_mods_xxxx','Controls the Object Linker processing for removing links between Preferred Vocab \"Subject\" Records and FBA PDF MODS \"Object\" Records when a Preferrred Vocab Record is purged after one or more FBA Library Records have been linked to it.','sparql',1),
 (28,'sp_ol_xxxx_pgeovoc_mads_creationdate_fbalib_mods_xxxx','Controls the Object Linker processing for removing links between Preferred GeoVoc \"Subject\" Records and FBA PDF MODS \"Object\" Records when a Preferrred GeoVoc Record is purged after one or more FBA Library Records have been linked to it.','sparql',1),
 (29,'sp_ol_xxxx_pvocab_mads_correl_pgeovoc_mads_correl','Controls the Object Linker processing for the \"Geographic Correlative\" field on a Preferred Vocab MADS \"Subject\" Record linking to a \"Subject Correlative\" field on a Preferred Geo MADS \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (30,'sp_ol_xxxx_pgeovoc_mads_correl_pvocab_mads_correl','Controls the Object Linker processing for the \"Subject Correlative\" field on a Preferred geoVocab \"Subject\" Record linking to a \"Geographic Correlative\" field on a Preferred Vocab MADS \"Object\" Record.','sparql',1),
 (33,'sp_ol_xxxx_fbalib_mods_depictstaxon_taxon_dwc_xxxx','Controls the Object Linker processing for the \"Depicts Taxon\" on an FBA  Library \"Subject\" Record linking to a Taxonomic \"Object\" Record.','sparql',1),
 (34,'sp_ol_xxxx_taxon_dwc_child_taxon_dwc_parent','Controls the Object Linker processing for the \"Child Name\" field on a Taxon DWC \"Subject\" Record linking to a \"Parent Name\" field on a Taxon DWC \"Object\" Record.','sparql',1),
 (35,'sp_ol_xxxx_taxon_dwc_parent_taxon_dwc_child','Controls the Object Linker processing for the \"Parent Name\" field on a Taxon DWC \"Subject\" Record linking to a \"Child Name\" field on a Taxon DWC \"Object\" Record.','sparql',1),
 (36,'sp_ol_xxxx_taxon_dwc_synonym_taxon_dwc_synonym','Controls the Object Linker processing for the \"Synonym Name\" field on a Taxon DWC \"Subject\" Record linking to a \"Synonym Name\" field on a Taxon DWC \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (37,'sp_ol_xxxx_fbalib_mods_typespecimen_taxon_dwc_xxxx','Controls the Object Linker processing for the \"Type Specimen\" field on an FBA Library \"Subject\" Record linking to a Taxon \"Object\" Record. Object Creation cannot be specified because this and \"depicts\" then produce duplicates.','sparql',1),
 (43,'sp_ol_xxxx_fbalib_mods_accesscond_licence_xxxx_xxxx','Controls the Object Linker processing for the \"Access Condition\" on an FBA Media \"Subject\" Record linking to a Licence \"Object\" Record.','sparql',1),
 (39,'sp_ol_xxxx_taxon_dwc_rank_literal_xxxx_xxxx','Controls the Object Linker literal-link processing for the \"Taxon Rank\" field on a Taxon DWC Record','sparql',1),
 (40,'sp_ol_xxxx_taxon_dwc_epithet_literal_xxxx_xxxx','Controls the Object Linker literal-link processing for the \"Specific Epithet\" field on a Taxon DWC Record','sparql',1),
 (41,'sp_ol_xxxx_taxon_dwc_status_literal_xxxx_xxxx','Controls the Object Linker literal-link processing for the \"Taxonomic Status\" field on a Taxon DWC Record','sparql',1),
 (42,'sp_ol_xxxx_taxon_dwc_subgroup_literal_xxxx_xxxx','Controls the Object Linker literal-link processing for the \"Subgroup\" field on a Taxon DWC Record','sparql',1);
/*!40000 ALTER TABLE `islandora_autocomplete` ENABLE KEYS */;


--
-- Table structure for table `drupal_data_fba_org_uk_test1`.`islandora_autocomplete_sparql`
--

DROP TABLE IF EXISTS `islandora_autocomplete_sparql`;
CREATE TABLE `islandora_autocomplete_sparql` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url_id` int(11) NOT NULL,
  `sparql_field` varchar(2048) NOT NULL,
  `rdf_relationship` varchar(256) NOT NULL,
  `subject_dsid` varchar(128) NOT NULL,
  `subject_namespace_info` varchar(2048) NOT NULL,
  `subject_xpath_title_search` varchar(1024) NOT NULL,
  `subject_xpath_data_search` varchar(1024) NOT NULL,
  `object_pid_append_required` int(11) NOT NULL,
  `object_creation_required` int(11) NOT NULL,
  `link_type` int(11) DEFAULT NULL,
  `symmetry_in_object_datastream_required` int(11) NOT NULL,
  `object_dsid` varchar(128) NOT NULL,
  `object_namespace_info` varchar(2048) NOT NULL,
  `object_datastream_xml` varchar(4096) NOT NULL,
  `object_xpath_title_search` varchar(1024) NOT NULL,
  `object_xpath_date_create_search` varchar(1024) NOT NULL,
  `object_content_model_pid` varchar(256) NOT NULL,
  `object_collection_pid` varchar(256) NOT NULL,
  `object_namespace_prefix` varchar(256) NOT NULL,
  `object_transform` varchar(1024) NOT NULL,
  `object_state` varchar(128) NOT NULL,
  `object_xpath_data_search` varchar(1024) NOT NULL,
  `object_xpath_data_build` varchar(1024) NOT NULL,
  `object_xpath_data_build_countback` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=66 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `drupal_data_fba_org_uk_test1`.`islandora_autocomplete_sparql`
--

/*!40000 ALTER TABLE `islandora_autocomplete_sparql` DISABLE KEYS */;
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (26,4,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#hasBroaderAuthority','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"broader\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic','/mads/related[@type=\"narrower\"]/topic','2'),
 (27,5,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabnonpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabnonpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#useFor','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><variant><topic></topic></variant><related otherType=\"use\" type=\"other\"><topic></topic></related><note type=\"approved date\"></note><recordInfo><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><identifier type=\"TNR\"></identifier></mads>','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabnonpref_CModel','fba:vocabnonpref_collection','vocabnonpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabnonpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"use\" and @type=\"other\" ]/topic','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (29,7,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasKeyword','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:subject[@authority=\"islandora subject\"]/mods:topic',0,0,0,0,'','','','','','','','','','','','',''),
 (53,31,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonomicKeyword','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:subject[@authority=\"fba taxonomic\"]/mods:topic',0,0,0,0,'','dwr!!rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms/==dcterms!!http://purl.org/dc/terms/','','','','fba:taxon_cmodel','fwltaxon:collection','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (32,10,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicKeyword','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:subject[@authority=\"islandora geographic\"]/mods:geographic',0,0,0,0,'','','','','','','','','','','','',''),
 (38,16,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geononpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geononpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#useFor','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><variant><topic></topic></variant><related otherType=\"use\" type=\"other\"><topic></topic></related><note type=\"approved date\"></note><recordInfo><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo></mads>','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geononpref_CModel','fba:geononpref_collection','geononpref','./sites/all/modules/islandora_content_model_forms/transforms/geononpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"use\" and @type=\"other\"]/topic','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (33,11,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#hasRelatedAuthority','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[not(@*)]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[not(@*)]/mads:topic','/mads/related/topic','2'),
 (34,12,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#hasNarrowerAuthority','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"broader\"]/mads:topic','/mads/related[@type=\"broader\"]/topic','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (35,13,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#hasBroaderAuthority','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"broader\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic','/mads/related[@type=\"narrower\"]/topic','2'),
 (36,14,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#hasNarrowerAuthority','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@type=\"narrower\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@type=\"broader\"]/mads:topic','/mads/related[@type=\"broader\"]/topic','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (37,15,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#hasRelatedAuthority','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[not(@*)]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[not(@*)]/mads:topic','/mads/related/topic','2'),
 (39,17,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicFeature','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"geographic feature\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"is geographic feature of\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"is geographic feature of\" and @type=\"other\"]/topic','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (40,18,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isGeographicFeatureOf','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"is geographic feature of\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"geographic feature\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"geographic feature\" and @type=\"other\"]/topic','2'),
 (41,19,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#useInstead','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"used for\" and @type=\"other\"]/topic','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (42,20,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://www.loc.gov/mads/rdf/v1#useInstead','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:variant/mads:topic','/mads:mads/mads:related[@otherType=\"use\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"used for\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"used for\" and @type=\"other\"]/topic','2'),
 (43,21,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/islandora:sp_strict_pdf>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/islandora:sp_pdf_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isGeographicKeywordedWith','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','',0,0,2,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (44,22,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/islandora:sp_strict_pdf>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/islandora:sp_pdf_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isKeywordedWith','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','',0,0,2,0,'','','','','','','','','','','','',''),
 (45,23,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasKeyword','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:subject[@authority=\"fba subject\"]/mods:topic',0,0,0,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (46,24,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicKeyword','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:subject[@authority=\"fba geographic\"]/mods:geographic',0,0,0,0,'','','','','','','','','','','','',''),
 (47,25,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasPreferredUnit','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"preferred unit\" and @type=\"other\"]/mads:topic',0,1,1,0,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (48,26,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isPreferredUnitOf','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','',0,0,1,0,'','','','','','','','','','','','',''),
 (49,27,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fbalc:collection> FILTER (regex(str(?title), \"^search_term_place_holder\", \"i\") && (sameTerm(?model, <info:fedora/fba:library_monograph_cmodel>) || sameTerm(?model, <info:fedora/fba:library_article_cmodel>) || sameTerm(?model, <info:fedora/fba:library_chapter_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isKeywordedWith','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','',0,0,2,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (50,28,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fbalc:collection> FILTER (regex(str(?title), \"^search_term_place_holder\", \"i\") && (sameTerm(?model, <info:fedora/fba:library_monograph_cmodel>) || sameTerm(?model, <info:fedora/fba:library_article_cmodel>) || sameTerm(?model, <info:fedora/fba:library_chapter_cmodel)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isGeographicKeywordedWith','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','',0,0,2,0,'','','','','','','','','','','','',''),
 (51,29,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasCorrelative','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"geographic correlative\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"geographic feature\" type=\"other\"><topic></topic></related><related otherType=\"is geographic feature of\" type=\"other\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"subject correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:geopref_CModel','fba:geopref_collection','geopref','./sites/all/modules/islandora_content_model_forms/transforms/geopref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"subject correlative\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"subject correlative\" and @type=\"other\"]/topic','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (52,30,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasCorrelative','MADS','mads!!http://www.loc.gov/mads/v2','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:related[@otherType=\"subject correlative\" and @type=\"other\"]/mads:topic',0,1,1,1,'MADS','mads!!http://www.loc.gov/mads/v2','<mads xmlns=\"http://www.loc.gov/mads/v2\"><authority><topic></topic></authority><note type=\"scope\"></note><related><topic></topic></related><related type=\"broader\"><topic></topic></related><related type=\"narrower\"><topic></topic></related><related otherType=\"used for\" type=\"other\"><topic></topic></related><related otherType=\"geographic correlative\" type=\"other\"><topic></topic></related><related otherType=\"preferred unit\" type=\"other\"><topic></topic></related><note type=\"definition\"></note><note type=\"definition source\"></note><note type=\"non-validity date\"></note><recordInfo xmlns:mads=\"http://www.loc.gov/mads/v2\"><recordCreationDate></recordCreationDate><recordChangeDate></recordChangeDate></recordInfo><note type=\"approved date\"></note></mads>','/mads:mads/mads:authority/mads:topic','/mads:mads/mads:recordInfo/mads:recordCreationDate','fba:vocabpref_CModel','fba:vocabpref_collection','vocabpref','./sites/all/modules/islandora_content_model_forms/transforms/vocabpref_mads_to_dc.xsl','A','/mads:mads/mads:related[@otherType=\"geographic correlative\" and @type=\"other\"]/mads:topic','/mads/related[@otherType=\"geographic correlative\" and @type=\"other\"]/topic','2'),
 (54,32,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fbalc:collection> FILTER (regex(str(?title), \"^search_term_place_holder\", \"i\") && (sameTerm(?model, <info:fedora/fba:library_monograph_cmodel>) || sameTerm(?model, <info:fedora/fba:library_article_cmodel>) || sameTerm(?model, <info:fedora/fba:library_chapter_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isTaxonomicKeywordedWith','DWC','dwr!!http://http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','',0,0,2,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (55,33,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://xmlns.com/foaf/spec/depicts','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:subject[@displayLabel=\"depicts taxon\"]/mods:name/mods:namePart',0,0,0,0,'DWC','dwr!!rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms/==dcterms!!http://purl.org/dc/terms/','','','','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','','','','',''),
 (63,41,'select ?text WHERE { <info:fedora/subject_pid_place_holder> \r\n<http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonomicStatus> ?text\r\n FILTER regex(str(?text), \"^search_term_place_holder\", \"i\")}','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonomicStatus','DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dwc:taxonomicStatus',0,0,3,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (65,43,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:licence_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:licence_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasLicence','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:accessCondition[@type=\"use and reproduction\"]',0,0,0,0,'','','','','','','','','','','','',''),
 (64,42,'select ?text WHERE { <info:fedora/subject_pid_place_holder> \r\n<http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasSubgroup> ?text\r\n FILTER regex(str(?text), \"^search_term_place_holder\", \"i\")}','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasSubgroup','DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dwc:subgroup/dwc:subgroupUsage',0,0,3,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (56,34,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasMostProximateChild','DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dwc:childName/dwc:childNameUsage',0,1,1,1,'DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','<DarwinRecordSet xmlns=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dwr=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dwc=\"http://rs.tdwg.org/dwc/terms/\"><dwc:Taxon><dwc:scientificName></dwc:scientificName><dwc:scientificNameAuthorship></dwc:scientificNameAuthorship><dwc:specificEpithet></dwc:specificEpithet><dwc:taxonRank></dwc:taxonRank><dwc:namePublishedIn></dwc:namePublishedIn><dwc:nomenclaturalCode></dwc:nomenclaturalCode><dwc:taxonomicStatus></dwc:taxonomicStatus><dwc:vernacularName></dwc:vernacularName><dwc:synonymName><dwc:synonymNameUsage></dwc:synonymNameUsage><dwc:synonymTaxonomicStatus></dwc:synonymTaxonomicStatus></dwc:synonymName><dwc:parentNameUsage></dwc:parentNameUsage><dwc:childName><dwc:childNameUsage></dwc:childNameUsage></dwc:childName><dwc:subgroup><dwc:subgroupUsage></dwc:subgroupUsage></dwc:subgroup><dwc:taxonRemarks></dwc:taxonRemarks><dcterms:modified></dcterms:modified></dwc:Taxon></DarwinRecordSet>','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dcterms:modified','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','./sites/all/modules/islandora_content_model_forms/transforms/dwc_taxon_to_dc.xsl','A','/dwr:DarwinRecordSet/dwc:Taxon/dwc:parentNameUsage','/dwr:DarwinRecordSet/dwc:Taxon/dwc:parentNameUsage','1'),
 (57,35,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasMostProximateParent','DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dwc:parentNameUsage',0,1,1,1,'DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','<DarwinRecordSet xmlns=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dwr=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dwc=\"http://rs.tdwg.org/dwc/terms/\"><dwc:Taxon><dwc:scientificName></dwc:scientificName><dwc:scientificNameAuthorship></dwc:scientificNameAuthorship><dwc:specificEpithet></dwc:specificEpithet><dwc:taxonRank></dwc:taxonRank><dwc:namePublishedIn></dwc:namePublishedIn><dwc:nomenclaturalCode></dwc:nomenclaturalCode><dwc:taxonomicStatus></dwc:taxonomicStatus><dwc:vernacularName></dwc:vernacularName><dwc:synonymName><dwc:synonymNameUsage></dwc:synonymNameUsage><dwc:synonymTaxonomicStatus></dwc:synonymTaxonomicStatus></dwc:synonymName><dwc:parentNameUsage></dwc:parentNameUsage><dwc:childName><dwc:childNameUsage></dwc:childNameUsage></dwc:childName><dwc:subgroup><dwc:subgroupUsage></dwc:subgroupUsage></dwc:subgroup><dwc:taxonRemarks></dwc:taxonRemarks><dcterms:modified></dcterms:modified></dwc:Taxon></DarwinRecordSet>','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dcterms:modified','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','./sites/all/modules/islandora_content_model_forms/transforms/dwc_taxon_to_dc.xsl','A','/dwr:DarwinRecordSet/dwc:Taxon/dwc:childName/dwc:childNameUsage','/dwr:DarwinRecordSet/dwc:Taxon/dwc:childName/dwc:childNameUsage','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (58,36,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasSynonym','DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dwc:synonymName/dwc:synonymNameUsage',0,1,1,1,'DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','<DarwinRecordSet xmlns=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dwr=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dwc=\"http://rs.tdwg.org/dwc/terms/\"><dwc:Taxon><dwc:scientificName></dwc:scientificName><dwc:scientificNameAuthorship></dwc:scientificNameAuthorship><dwc:specificEpithet></dwc:specificEpithet><dwc:taxonRank></dwc:taxonRank><dwc:namePublishedIn></dwc:namePublishedIn><dwc:nomenclaturalCode></dwc:nomenclaturalCode><dwc:taxonomicStatus></dwc:taxonomicStatus><dwc:vernacularName></dwc:vernacularName><dwc:synonymName><dwc:synonymNameUsage></dwc:synonymNameUsage><dwc:synonymTaxonomicStatus></dwc:synonymTaxonomicStatus></dwc:synonymName><dwc:parentNameUsage></dwc:parentNameUsage><dwc:childName><dwc:childNameUsage></dwc:childNameUsage></dwc:childName><dwc:subgroup><dwc:subgroupUsage></dwc:subgroupUsage></dwc:subgroup><dwc:taxonRemarks></dwc:taxonRemarks><dcterms:modified></dcterms:modified></dwc:Taxon></DarwinRecordSet>','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dcterms:modified','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','./sites/all/modules/islandora_content_model_forms/transforms/dwc_taxon_to_dc.xsl','A','/dwr:DarwinRecordSet/dwc:Taxon/dwc:synonymName/dwc:synonymNameUsage','/dwr:DarwinRecordSet/dwc:Taxon/dwc:synonymName/dwc:synonymNameUsage','2'),
 (59,37,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isTypeSpecimenFor','MODS','mods!!http://www.loc.gov/mods/v3','/mods:mods/mods:titleInfo','/mods:mods/mods:relatedItem[@type=\"original\"]/mods:note[@type=\"taxonomic type specimen for\"]',0,0,0,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (62,40,'select ?text WHERE { <info:fedora/subject_pid_place_holder> \r\n<http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonSpecificEpithet> ?text\r\n FILTER regex(str(?text), \"^search_term_place_holder\", \"i\")}','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonSpecificEpithet','DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dwc:specificEpithet',0,0,3,0,'','','','','','','','','','','','',''),
 (61,39,'select ?text WHERE { <info:fedora/subject_pid_place_holder> \r\n<http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonRank> ?text\r\n FILTER regex(str(?text), \"^search_term_place_holder\", \"i\")}','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonRank','DWC','dwr!!http://rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms==dcterms!!http://purl.org/dc/terms','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dwc:taxonRank',0,0,3,0,'','','','','','','','','','','','','');
/*!40000 ALTER TABLE `islandora_autocomplete_sparql` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
