-- MySQL Administrator dump 1.4
--
-- ------------------------------------------------------
-- Server version	5.1.73-log


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


--
-- Create schema drupal_mydata_envdata_test1
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ drupal_mydata_envdata_test1;
USE drupal_mydata_envdata_test1;

--
-- Table structure for table `drupal_mydata_envdata_test1`.`islandora_autocomplete`
--

DROP TABLE IF EXISTS `islandora_autocomplete`;
CREATE TABLE `islandora_autocomplete` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `description` varchar(256) NOT NULL,
  `source` varchar(64) NOT NULL,
  `fields` int(11) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  KEY `source` (`source`)
) ENGINE=MyISAM AUTO_INCREMENT=38 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `drupal_mydata_envdata_test1`.`islandora_autocomplete`
--

/*!40000 ALTER TABLE `islandora_autocomplete` DISABLE KEYS */;
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (1,'sp_ol_dtca_datacomp_dtca_input_datacomp_xxxx_xxxx','Controls the Object Linker processing for the \"Input\" field on any Data-Component \"Subject\" Record linking to a Data-Component-Measurement or supplementary file \"Object\" Record.','sparql',1),
 (2,'sp_ol_dtca_activity_dtca_vocabkeyw_pvocab_mads_xxxx','Controls the Object Linker processing for the \"Vocab Keyword\" on a DTCA Activity \"Subject\" Record linking to a Preferred Vocab \"Object\" Record.','sparql',1),
 (3,'sp_ol_dtca_activity_dtca_geokeyw_pgeovoc_mads_xxxx','Controls the Object Linker processing for the \"Geographic Keyword\" on a DTCA Activity \"Subject\" Record linking to a Preferred geoVocab \"Object\" Record.','sparql',1),
 (4,'sp_ol_dtca_dataset_dtca_vocabkeyw_pvocab_mads_xxxx','Controls the Object Linker processing for the \"Vocab Keyword\" on a DTCA Dataset \"Subject\" Record linking to a Preferred Vocab \"Object\" Record.','sparql',1),
 (5,'sp_ol_dtca_dataset_dtca_geokeyw_pgeovoc_mads_xxxx','Controls the Object Linker processing for the \"Geographic Keyword\" on a DTCA Dataset \"Subject\" Record linking to a Preferred geoVocab \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (6,'sp_ol_dtca_datacomp_dtca_vocabkeyw_pvocab_mads_xxxx','Controls the Object Linker processing for the \"Vocab Keyword\" on a DTCA Data-component \"Subject\" Record linking to a Preferred Vocab \"Object\" Record.','sparql',1),
 (7,'sp_ol_dtca_datacomp_dtca_geokeyw_pgeovoc_mads_xxxx','Controls the Object Linker processing for the \"Geographic Keyword\" on a DTCA Data-component \"Subject\" Record linking to a Preferred geoVocab \"Object\" Record.','sparql',1),
 (21,'sp_ol_dtca_datacomp_dtca_proto_datacomp_xxxx_xxxx','Controls the Object Linker processing for the \"Internal Protocol\" field on any Data-Component \"Subject\" Record linking to a supplementary file \"Object\" Record.','sparql',1),
 (10,'sp_ol_dtca_activity_dtca_taxonkeyw_taxon_dwc_xxxx','Controls the Object Linker processing for the \"Taxonomic Keyword\" on a DTCA Activity \"Subject\" Record linking to a Taxonomic \"Object\" Record.','sparql',1),
 (11,'sp_ol_dtca_dataset_dtca_taxonkeyw_taxon_dwc_xxxx','Controls the Object Linker processing for the \"Taxonomic Keyword\" on a DTCA Dataset \"Subject\" Record linking to a Taxonomic \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (12,'sp_ol_dtca_datacomp_dtca_taxonkeyw_taxon_dwc_xxxx','Controls the Object Linker processing for the \"Taxonomic Keyword\" on a DTCA Data-component \"Subject\" Record linking to a Taxonomic \"Object\" Record.','sparql',1),
 (19,'sp_ol_dtca_datacomp_dtca_docum_datacomp_xxxx_xxxx','Controls the Object Linker processing for the \"Internal Documentation\" field on any Data-Component \"Subject\" Record linking to a supplementary file \"Object\" Record.','sparql',1),
 (18,'sp_ol_dtca_datacomp_dtca_linkcontrol_datacomp_dtca_input','Controls the Object Linker processing for editing and removing input links between a data component \"Subject\" Record and other Data Component \"Object\" Records when a data component is purged or its title is edited','sparql',1),
 (20,'sp_ol_dtca_datacomp_dtca_design_datacomp_xxxx_xxxx','Controls the Object Linker processing for the \"Internal Design\" field on any Data-Component \"Subject\" Record linking to a supplementary file \"Object\" Record.','sparql',1),
 (27,'sp_ol_dtca_datacomp_dtca_depictstaxon_taxon_dwc_xxxx','Controls the Object Linker processing for the \"Depicts Taxon\" field on a DTCA Data-component-supplementary \"Subject\" Record linking to a Taxonomic \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (28,'sp_ol_dtca_datacomp_dtca_linkcontrol_datacomp_dtca_docum','Controls the Object Linker processing for editing and removing documentation links between a data component \"Subject\" Record and other Data Component \"Object\" Records when a data component is purged or its title is edited','sparql',1),
 (29,'sp_ol_dtca_datacomp_dtca_linkcontrol_datacomp_dtca_proto','Controls the Object Linker processing for editing and removing protocol links between a data component \"Subject\" Record and other Data Component \"Object\" Records when a data component is purged or its title is edited','sparql',1),
 (30,'sp_ol_dtca_datacomp_dtca_linkcontrol_datacomp_dtca_design','Controls the Object Linker processing for editing and removing design links between a data component \"Subject\" Record and other Data Component \"Object\" Records when a data component is purged or its title is edited','sparql',1),
 (32,'sp_ol_dtca_dataset_dtca_docum_datacomp_xxxx_xxxx','Controls the Object Linker processing for the \"Internal Documentation\" field on a Dataset \"Subject\" Record linking to a supplementary file \"Object\" Record.','sparql',1),
 (33,'sp_ol_dtca_dataset_dtca_design_datacomp_xxxx_xxxx','Controls the Object Linker processing for the \"Internal Design\" field on a Dataset \"Subject\" Record linking to a supplementary file \"Object\" Record.','sparql',1);
INSERT INTO `islandora_autocomplete` (`id`,`name`,`description`,`source`,`fields`) VALUES 
 (34,'sp_ol_dtca_dataset_dtca_proto_datacomp_xxxx_xxxx','Controls the Object Linker processing for the \"Internal Protocol\" field on a Dataset \"Subject\" Record linking to a supplementary file \"Object\" Record.','sparql',1),
 (35,'sp_ol_dtca_datacomp_dtca_linkcontrol_dataset_dtca_docum','Controls the Object Linker processing for editing and removing documentation links between a data component \"Subject\" Record and an Dataset \"Object\" Record when a data component is purged or its title is edited','sparql',1),
 (36,'sp_ol_dtca_datacomp_dtca_linkcontrol_dataset_dtca_design','Controls the Object Linker processing for editing and removing design links between a data component \"Subject\" Record and an Dataset \"Object\" Record when a data component is purged or its title is edited','sparql',1),
 (37,'sp_ol_dtca_datacomp_dtca_linkcontrol_dataset_dtca_proto','Controls the Object Linker processing for editing and removing protocol links between a data component \"Subject\" Record and an Dataset \"Object\" Record when a data component is purged or its title is edited','sparql',1);
/*!40000 ALTER TABLE `islandora_autocomplete` ENABLE KEYS */;


--
-- Table structure for table `drupal_mydata_envdata_test1`.`islandora_autocomplete_sparql`
--

DROP TABLE IF EXISTS `islandora_autocomplete_sparql`;
CREATE TABLE `islandora_autocomplete_sparql` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url_id` int(11) NOT NULL,
  `sparql_field` varchar(2048) NOT NULL,
  `rdf_relationship` varchar(256) NOT NULL,
  `subject_dsid` varchar(128) NOT NULL,
  `subject_namespace_info` varchar(2048) NOT NULL,
  `subject_xpath_title_search` varchar(1024) NOT NULL,
  `subject_xpath_data_search` varchar(1024) NOT NULL,
  `object_pid_append_required` int(11) NOT NULL,
  `object_creation_required` int(11) NOT NULL,
  `link_type` int(11) DEFAULT NULL,
  `symmetry_in_object_datastream_required` int(11) NOT NULL,
  `object_dsid` varchar(128) NOT NULL,
  `object_namespace_info` varchar(2048) NOT NULL,
  `object_datastream_xml` varchar(4096) NOT NULL,
  `object_xpath_title_search` varchar(1024) NOT NULL,
  `object_xpath_date_create_search` varchar(1024) NOT NULL,
  `object_content_model_pid` varchar(256) NOT NULL,
  `object_collection_pid` varchar(256) NOT NULL,
  `object_namespace_prefix` varchar(256) NOT NULL,
  `object_transform` varchar(1024) NOT NULL,
  `object_state` varchar(128) NOT NULL,
  `object_xpath_data_search` varchar(1024) NOT NULL,
  `object_xpath_data_build` varchar(1024) NOT NULL,
  `object_xpath_data_build_countback` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=37 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `drupal_mydata_envdata_test1`.`islandora_autocomplete_sparql`
--

/*!40000 ALTER TABLE `islandora_autocomplete_sparql` DISABLE KEYS */;
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (1,1,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> ?collection FILTER( (regex(str(?title), \"^search_term_place_holder\", \"i\") && sameTerm(?collection, <user_collection_place_holder>)) && !sameTerm(?model, <info:fedora/fba:activity_cmodel>)  && !sameTerm(?model, <info:fedora/fba:dataset_cmodel>) && !sameTerm(?model, <info:fedora/si:conceptCModel>) && !sameTerm(?model, <info:fedora/fedora-system:FedoraObject-3.0>))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasComponentInput','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:input/gco:CharacterString',0,0,2,0,'','','','','','','','','','','','',''),
 (2,2,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==gco!!http://isotc211.org/2005/gco','/dtca:Activity/dtca:title','/dtca:Activity/dtca:keyword[@authority=\"fba subject\"]/gco:CharacterString',0,0,0,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (3,3,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:Activity/dtca:title','/dtca:Activity/dtca:keyword[@authority=\"fba geographic\"]/gco:CharacterString',0,0,0,0,'','','','','','','','','','','','',''),
 (26,27,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://xmlns.com/foaf/spec/depicts','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:keyword[@authority=\"fba depicts taxon\"]/gco:CharacterString',0,1,0,0,'DWC','dwr!!rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms/==dcterms!!http://purl.org/dc/terms/','<DarwinRecordSet xmlns=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dwr=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dwc=\"http://rs.tdwg.org/dwc/terms/\"><dwc:Taxon><dwc:scientificName></dwc:scientificName><dwc:scientificNameAuthorship></dwc:scientificNameAuthorship><dwc:specificEpithet></dwc:specificEpithet><dwc:taxonRank></dwc:taxonRank><dwc:namePublishedIn></dwc:namePublishedIn><dwc:nomenclaturalCode></dwc:nomenclaturalCode><dwc:taxonomicStatus></dwc:taxonomicStatus><dwc:vernacularName></dwc:vernacularName><dwc:synonymName><dwc:synonymNameUsage></dwc:synonymNameUsage><dwc:synonymTaxonomicStatus></dwc:synonymTaxonomicStatus></dwc:synonymName><dwc:parentNameUsage></dwc:parentNameUsage><dwc:childName><dwc:childNameUsage></dwc:childNameUsage></dwc:childName><dwc:subgroup><dwc:subgroupUsage></dwc:subgroupUsage></dwc:subgroup><dwc:taxonRemarks></dwc:taxonRemarks><dcterms:modified></dcterms:modified></dwc:Taxon></DarwinRecordSet>','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dcterms:modified','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','./sites/all/modules/islandora_content_model_forms/transforms/dwc_taxon_to_dc.xsl','A','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (4,4,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:Dataset/dtca:title','/dtca:Dataset/dtca:keyword[@authority=\"fba subject\"]/gco:CharacterString',0,0,0,0,'','','','','','','','','','','','',''),
 (5,5,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:Dataset/dtca:title','/dtca:Dataset/dtca:keyword[@authority=\"fba geographic\"]/gco:CharacterString',0,0,0,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (6,6,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:vocabpref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:vocabpref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:keyword[@authority=\"fba subject\"]/gco:CharacterString',0,0,0,0,'MADS','','','','','','','','','','','',''),
 (7,7,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:geopref_CModel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fba:geopref_collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasGeographicKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:keyword[@authority=\"fba geographic\"]/gco:CharacterString',0,0,0,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (19,20,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> ?collection FILTER( (regex(str(?title), \"^search_term_place_holder\", \"i\") && sameTerm(?collection, <user_collection_place_holder>)) && (sameTerm(?model, <info:fedora/fba:supp_pdf_cmodel>)  || sameTerm(?model, <info:fedora/fba:supp_text_cmodel>) || sameTerm(?model, <info:fedora/fba:supp_word_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasDesign','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:design[@type=\"internal\"]/gmd:CI_OnlineResource/gmd:description',0,0,0,0,'','','','','','','','','','','','',''),
 (20,21,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> ?collection FILTER( (regex(str(?title), \"^search_term_place_holder\", \"i\") && sameTerm(?collection, <user_collection_place_holder>)) && (sameTerm(?model, <info:fedora/fba:supp_pdf_cmodel>)  || sameTerm(?model, <info:fedora/fba:supp_text_cmodel>) || sameTerm(?model, <info:fedora/fba:supp_word_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasProtocol','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:protocol[@type=\"internal\"]/gmd:CI_OnlineResource/gmd:description',0,0,0,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (11,11,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonomicKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==gco!!http://isotc211.org/2005/gco','/dtca:Dataset/dtca:title','/dtca:Dataset/dtca:keyword[@authority=\"fba taxonomic\"]/gco:CharacterString',0,1,0,0,'DWC','dwr!!rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms/==dcterms!!http://purl.org/dc/terms/','<DarwinRecordSet xmlns=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dwr=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dwc=\"http://rs.tdwg.org/dwc/terms/\"><dwc:Taxon><dwc:scientificName></dwc:scientificName><dwc:scientificNameAuthorship></dwc:scientificNameAuthorship><dwc:specificEpithet></dwc:specificEpithet><dwc:taxonRank></dwc:taxonRank><dwc:namePublishedIn></dwc:namePublishedIn><dwc:nomenclaturalCode></dwc:nomenclaturalCode><dwc:taxonomicStatus></dwc:taxonomicStatus><dwc:vernacularName></dwc:vernacularName><dwc:synonymName><dwc:synonymNameUsage></dwc:synonymNameUsage><dwc:synonymTaxonomicStatus></dwc:synonymTaxonomicStatus></dwc:synonymName><dwc:parentNameUsage></dwc:parentNameUsage><dwc:childName><dwc:childNameUsage></dwc:childNameUsage></dwc:childName><dwc:subgroup><dwc:subgroupUsage></dwc:subgroupUsage></dwc:subgroup><dwc:taxonRemarks></dwc:taxonRemarks><dcterms:modified></dcterms:modified></dwc:Taxon></DarwinRecordSet>','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dcterms:modified','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','./sites/all/modules/islandora_content_model_forms/transforms/dwc_taxon_to_dc.xsl','A','','',''),
 (17,18,'Not required for this processing','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isComponentInputOf','DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0','/dtca:DataComponent/dtca:title','',0,0,0,1,'DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0==gco!!http://www.isotc211.org/2005/gco','','','','','','','','','/dtca:DataComponent/dtca:input/gco:CharacterString','/DataComponent/input/CharacterSting','2');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (10,10,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonomicKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==gco!!http://isotc211.org/2005/gco','/dtca:Activity/dtca:title','/dtca:Activity/dtca:keyword[@authority=\"fba taxonomic\"]/gco:CharacterString',0,1,0,0,'DWC','dwr!!rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms/==dcterms!!http://purl.org/dc/terms/','<DarwinRecordSet xmlns=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dwr=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dwc=\"http://rs.tdwg.org/dwc/terms/\"><dwc:Taxon><dwc:scientificName></dwc:scientificName><dwc:scientificNameAuthorship></dwc:scientificNameAuthorship><dwc:specificEpithet></dwc:specificEpithet><dwc:taxonRank></dwc:taxonRank><dwc:namePublishedIn></dwc:namePublishedIn><dwc:nomenclaturalCode></dwc:nomenclaturalCode><dwc:taxonomicStatus></dwc:taxonomicStatus><dwc:vernacularName></dwc:vernacularName><dwc:synonymName><dwc:synonymNameUsage></dwc:synonymNameUsage><dwc:synonymTaxonomicStatus></dwc:synonymTaxonomicStatus></dwc:synonymName><dwc:parentNameUsage></dwc:parentNameUsage><dwc:childName><dwc:childNameUsage></dwc:childNameUsage></dwc:childName><dwc:subgroup><dwc:subgroupUsage></dwc:subgroupUsage></dwc:subgroup><dwc:taxonRemarks></dwc:taxonRemarks><dcterms:modified></dcterms:modified></dwc:Taxon></DarwinRecordSet>','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dcterms:modified','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','./sites/all/modules/islandora_content_model_forms/transforms/dwc_taxon_to_dc.xsl','A','','',''),
 (12,12,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> <info:fedora/fba:taxon_cmodel>; <fedora-rels-ext:isMemberOfCollection> <info:fedora/fwltaxon:collection> FILTER regex(str(?title), \"^search_term_place_holder\", \"i\") } ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasTaxonomicKeyword','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:keyword[@authority=\"fba taxonomic\"]/gco:CharacterString',0,1,0,0,'DWC','dwr!!rs.tdwg.org/dwc/dwcrecord==dwc!!http://rs.tdwg.org/dwc/terms/==dcterms!!http://purl.org/dc/terms/','<DarwinRecordSet xmlns=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dwr=\"http://rs.tdwg.org/dwc/dwcrecord\" xmlns:dwc=\"http://rs.tdwg.org/dwc/terms/\"><dwc:Taxon><dwc:scientificName></dwc:scientificName><dwc:scientificNameAuthorship></dwc:scientificNameAuthorship><dwc:specificEpithet></dwc:specificEpithet><dwc:taxonRank></dwc:taxonRank><dwc:namePublishedIn></dwc:namePublishedIn><dwc:nomenclaturalCode></dwc:nomenclaturalCode><dwc:taxonomicStatus></dwc:taxonomicStatus><dwc:vernacularName></dwc:vernacularName><dwc:synonymName><dwc:synonymNameUsage></dwc:synonymNameUsage><dwc:synonymTaxonomicStatus></dwc:synonymTaxonomicStatus></dwc:synonymName><dwc:parentNameUsage></dwc:parentNameUsage><dwc:childName><dwc:childNameUsage></dwc:childNameUsage></dwc:childName><dwc:subgroup><dwc:subgroupUsage></dwc:subgroupUsage></dwc:subgroup><dwc:taxonRemarks></dwc:taxonRemarks><dcterms:modified></dcterms:modified></dwc:Taxon></DarwinRecordSet>','/dwr:DarwinRecordSet/dwc:Taxon/dwc:scientificName','/dwr:DarwinRecordSet/dwc:Taxon/dcterms:modified','fba:taxon_cmodel','fwltaxon:collection','fwltaxon','./sites/all/modules/islandora_content_model_forms/transforms/dwc_taxon_to_dc.xsl','A','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (18,19,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> ?collection FILTER( (regex(str(?title), \"^search_term_place_holder\", \"i\") && sameTerm(?collection, <user_collection_place_holder>)) && (sameTerm(?model, <info:fedora/fba:supp_pdf_cmodel>)  || sameTerm(?model, <info:fedora/fba:supp_text_cmodel>) || sameTerm(?model, <info:fedora/fba:supp_word_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasDocumentation','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:DataComponent/dtca:title','/dtca:DataComponent/dtca:documentation[@type=\"internal\"]/gmd:CI_OnlineResource/gmd:description',0,0,0,0,'','','','','','','','','','','','',''),
 (27,28,'Not required for this processing','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isDocumentationFor','DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0','/dtca:DataComponent/dtca:title','',0,0,2,1,'DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','','','','','','','','','/*/dtca:documentation[@type=\"internal\"]/gmd:CI_OnlineResource[@id=\"doi1\"]/gmd:description','/DataComponent/documentation[@type=\"internal\"]/CI_OnlineResource[@id=\"doi1\"]/description','3');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (28,29,'Not required for this processing','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isProtocolFor','DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0','/dtca:DataComponent/dtca:title','',0,0,2,1,'DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','','','','','','','','','/dtca:DataComponent/dtca:protocol[@type=\"internal\"]/gmd:CI_OnlineResource[@id=\"pri1\"]/gmd:description','/DataComponent/protocol[@type=\"internal\"]/CI_OnlineResource[@id=\"pri1\"]/description','3'),
 (29,30,'Not required for this processing','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isDesignFor','DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0','/dtca:DataComponent/dtca:title','',0,0,2,1,'DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','','','','','','','','','/dtca:DataComponent/dtca:design[@type=\"internal\"]/gmd:CI_OnlineResource[@id=\"dei1\"]/gmd:description','/DataComponent/design[@type=\"internal\"]/CI_OnlineResource[@id=\"dei1\"]/description','3');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (31,32,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> ?collection FILTER( (regex(str(?title), \"^search_term_place_holder\", \"i\") && sameTerm(?collection, <user_collection_place_holder>)) && (sameTerm(?model, <info:fedora/fba:supp_pdf_cmodel>)  || sameTerm(?model, <info:fedora/fba:supp_text_cmodel>) || sameTerm(?model, <info:fedora/fba:supp_word_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasDocumentation','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:Dataset/dtca:title','/dtca:Dataset/dtca:documentation[@type=\"internal\"]/gmd:CI_OnlineResource/gmd:description',0,0,0,0,'','','','','','','','','','','','',''),
 (32,33,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> ?collection FILTER( (regex(str(?title), \"^search_term_place_holder\", \"i\") && sameTerm(?collection, <user_collection_place_holder>)) && (sameTerm(?model, <info:fedora/fba:supp_pdf_cmodel>)  || sameTerm(?model, <info:fedora/fba:supp_text_cmodel>) || sameTerm(?model, <info:fedora/fba:supp_word_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasDesign','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:Dataset/dtca:title','/dtca:Dataset/dtca:design[@type=\"internal\"]/gmd:CI_OnlineResource/gmd:description',0,0,0,0,'','','','','','','','','','','','','');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (33,34,'SELECT ?title ?object WHERE { ?object <http://purl.org/dc/elements/1.1/title> ?title; <fedora-model:state> <fedora-model:Active>; <fedora-model:hasModel> ?model; <fedora-rels-ext:isMemberOfCollection> ?collection FILTER( (regex(str(?title), \"^search_term_place_holder\", \"i\") && sameTerm(?collection, <user_collection_place_holder>)) && (sameTerm(?model, <info:fedora/fba:supp_pdf_cmodel>)  || sameTerm(?model, <info:fedora/fba:supp_text_cmodel>) || sameTerm(?model, <info:fedora/fba:supp_word_cmodel>)))} ORDER BY ?title','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/hasProtocol','DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','/dtca:Dataset/dtca:title','/dtca:Dataset/dtca:protocol[@type=\"internal\"]/gmd:CI_OnlineResource/gmd:description',0,0,0,0,'','','','','','','','','','','','',''),
 (34,35,'Not required for this processing','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isDocumentationFor','DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0','/dtca:DataComponent/dtca:title','',0,0,2,1,'DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','','','','','','','','','/*/dtca:documentation[@type=\"internal\"]/gmd:CI_OnlineResource[@id=\"doi1\"]/gmd:description','/Dataset/documentation[@type=\"internal\"]/CI_OnlineResource[@id=\"doi1\"]/description','3');
INSERT INTO `islandora_autocomplete_sparql` (`id`,`url_id`,`sparql_field`,`rdf_relationship`,`subject_dsid`,`subject_namespace_info`,`subject_xpath_title_search`,`subject_xpath_data_search`,`object_pid_append_required`,`object_creation_required`,`link_type`,`symmetry_in_object_datastream_required`,`object_dsid`,`object_namespace_info`,`object_datastream_xml`,`object_xpath_title_search`,`object_xpath_date_create_search`,`object_content_model_pid`,`object_collection_pid`,`object_namespace_prefix`,`object_transform`,`object_state`,`object_xpath_data_search`,`object_xpath_data_build`,`object_xpath_data_build_countback`) VALUES 
 (35,36,'Not required for this processing','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isDocumentationFor','DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0','/dtca:DataComponent/dtca:title','',0,0,2,1,'','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','','','','','','','','','/*/dtca:design[@type=\"internal\"]/gmd:CI_OnlineResource[@id=\"dei1\"]/gmd:description','/Dataset/design[@type=\"internal\"]/CI_OnlineResource[@id=\"dei1\"]/description','3'),
 (36,37,'Not required for this processing','http://fba.org.uk/schemas/fba/fba_rdf/1.0.0/isProtocolFor','DTCA','dtca!!http://fba.org.uk/schemas/schemas/dtca/1.0.0','/dtca:DataComponent/dtca:title','',0,0,2,1,'DTCA','dtca!!http://172.16.0.99/schemas/dtca/1.0.0==mo!!http://172.16.0.99/schemas/moles/3.4.0==gml!!http://opengis.net/gml==gmd!!http://isotc211.org/2005/gmd==gco!!http://isotc211.org/2005/gco','','','','','','','','','/*/dtca:protocol[@type=\"internal\"]/gmd:CI_OnlineResource[@id=\"pri1\"]/gmd:description','/Dataset/protocol[@type=\"internal\"]/CI_OnlineResource[@id=\"pri1\"]/description','3');
/*!40000 ALTER TABLE `islandora_autocomplete_sparql` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
